apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: example-prometheus-rule
spec:
  groups:
    - name: example
      rules:
        - alert: HighPodFailures
          expr: count(up == 0) > 1
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "High Pod Failures"